global using System.Linq.Expressions;
global using System.Text.Json;
// External dependencies
global using Bogus;
global using AutoFixture;
global using Moq;
global using Shouldly;
global using Xunit;
global using Xunit.Abstractions;
// Internal dependencies
global using Jsondyno.Misc;
global using Jsondyno.Tests.Fixtures;
global using Jsondyno.Tests.Misc;